# Generated by Django 3.2 on 2023-12-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_employeeinfo_employeeprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='networknode',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='network_nodes', to='webapp.EmployeeProfileInfo'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='network_level',
            field=models.IntegerField(choices=[(0, 'Factory'), (1, 'Distributor'), (2, 'Dealer Center'), (3, 'Retail Chain'), (4, 'Entrepreneur')], default=0),
        ),
    ]
