# Generated by Django 3.2 on 2023-12-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20231219_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='Contact',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='contacts',
        ),
        migrations.AddField(
            model_name='networknode',
            name='contact',
            field=models.OneToOneField(blank=True, help_text='Contact information for the network node', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_node', to='webapp.contact'),
        ),
    ]
